### ISSUE TITLE
How to use the code?

### ISSUE THREAD

**Issue by tuanpembual** [asyrofqomaruddin/ojekonline#1]
Haloo,
Adakah dokumen yg bisa saya baca untuk menggunakan kode dari repo ini?

Salam
Estu - Binar

**Comment by asyrofqomaruddin** [comment]
ahh maaf belum ada ya.

Anda bisa ngepush itu ke heroku atau ngerun di local (assuming sudah ada
ruby dan rails).

saat ini belum ada login ,
untuk melihat routes ada di config/routes.

karena belum ada cara membuat token, maaf sekali harus masuk ke consolenya
untuk membuat token+usernya...

saat ini yang ada hanyalah melihat profile user(yang cuman nama) dan
mengupdate nama user


2017-05-13 7:41 GMT+07:00 Estu Fardani <notifications@github.com>:

**Comment by tuanpembual** [comment]
terimakasih
